/*
 * MainFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.lts.client;
import com.lts.server;

import java.awt.Font;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author  __USER__
 */
public class MainFrm extends javax.swing.JFrame {

	/** Creates new form MainFrm */
	public MainFrm() {
		initComponents();
		//设置最大 化
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		table = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u5356\u5BB6\u670D\u52A1\u4E2D\u5FC3");

		setJMenuBar(jMenuBar1);
		jMenu3 = new javax.swing.JMenu();
		jMenu3.setFont(new Font("微软雅黑", Font.PLAIN, 12));
		jMenuBar1.add(jMenu3);
		jmiProductTypeAdd = new javax.swing.JMenuItem();
		jmiProductTypeModify = new javax.swing.JMenuItem();
		
				jMenu3.setIcon(null); // NOI18N
				jMenu3.setText("\u5546\u54c1\u79cd\u7c7b\u7ba1\u7406");
				
						jmiProductTypeAdd.setIcon(null); // NOI18N
						jmiProductTypeAdd.setText("\u5546\u54c1\u7c7b\u522b\u6dfb\u52a0");
						jmiProductTypeAdd
								.addActionListener(new java.awt.event.ActionListener() {
									public void actionPerformed(java.awt.event.ActionEvent evt) {
										jmiProductTypeAddActionPerformed(evt);
									}
								});
						jMenu3.add(jmiProductTypeAdd);
						
								jmiProductTypeModify.setIcon(null); // NOI18N
								jmiProductTypeModify.setText("\u5546\u54c1\u7c7b\u522b\u7ef4\u62a4");
								jmiProductTypeModify
										.addActionListener(new java.awt.event.ActionListener() {
											public void actionPerformed(java.awt.event.ActionEvent evt) {
												jmiProductTypeModifyActionPerformed(evt);
											}
										});
								jMenu3.add(jmiProductTypeModify);
								jMenu4 = new javax.swing.JMenu();
								jMenu4.setFont(new Font("微软雅黑", Font.PLAIN, 12));
								jMenuBar1.add(jMenu4);
								jmiProductAdd = new javax.swing.JMenuItem();
								jmiProductModify = new javax.swing.JMenuItem();
								
										jMenu4
												.setIcon(null); // NOI18N
										jMenu4.setText("\u5546\u54c1\u7ba1\u7406");
										
												jmiProductAdd.setIcon(null); // NOI18N
												jmiProductAdd.setText("\u5546\u54c1\u6dfb\u52a0");
												jmiProductAdd.addActionListener(new java.awt.event.ActionListener() {
													public void actionPerformed(java.awt.event.ActionEvent evt) {
														jmiProductAddActionPerformed(evt);
													}
												});
												jMenu4.add(jmiProductAdd);
												
														jmiProductModify.setIcon(null); // NOI18N
														jmiProductModify.setText("\u5546\u54c1\u7ef4\u62a4");
														jmiProductModify.addActionListener(new java.awt.event.ActionListener() {
															public void actionPerformed(java.awt.event.ActionEvent evt) {
																jmiProductModifyActionPerformed(evt);
															}
														});
														jMenu4.add(jmiProductModify);
														
														menu = new JMenu();
														menu.addMouseListener(new MouseAdapter() {
															@Override
															public void mouseClicked(MouseEvent arg0) {
																server a=new server();
																a.frame.setVisible(true); 
															}
														});
												
														menu.setText("\u901A\u8BAF\u5DE5\u5177");
														menu.setFont(new Font("微软雅黑", Font.PLAIN, 12));
														jMenuBar1.add(menu);
														
														menu_1 = new JMenu();
														menu_1.addMouseListener(new MouseAdapter() {
															@Override
															public void mouseClicked(MouseEvent arg0) {
																new alleva().show();
															}
														});
														menu_1.setText("\u6240\u6709\u8BC4\u4EF7");
														menu_1.setFont(new Font("微软雅黑", Font.PLAIN, 12));
														jMenuBar1.add(menu_1);
														jmiExit = new javax.swing.JMenuItem();
														jmiExit.setFont(new Font("微软雅黑", Font.PLAIN, 12));
														jMenuBar1.add(jmiExit);
														
																jmiExit.setIcon(null); // NOI18N
																jmiExit.setText("\u9000\u51fa\u7cfb\u7edf");
																jmiExit.addActionListener(new java.awt.event.ActionListener() {
																	public void actionPerformed(java.awt.event.ActionEvent evt) {
																		jmiExitActionPerformed(evt);
																	}
																});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents


	
	private void jmiProductModifyActionPerformed(java.awt.event.ActionEvent evt) {
		ProductManageInterFrm ProductManageInterFrm = new ProductManageInterFrm();
		ProductManageInterFrm.setVisible(true);
		this.table.add(ProductManageInterFrm);
	}

	private void jmiProductAddActionPerformed(java.awt.event.ActionEvent evt) {
		ProductAddInterFrm ProductAddInterFrm = new ProductAddInterFrm();
		ProductAddInterFrm.setVisible(true);
		this.table.add(ProductAddInterFrm);
	}

	private void jmiProductTypeModifyActionPerformed(
			java.awt.event.ActionEvent evt) {
		ProductTypeManageInterFrm ProductTypeManageInterFrm = new ProductTypeManageInterFrm();
		ProductTypeManageInterFrm.setVisible(true);
		this.table.add(ProductTypeManageInterFrm);
	}

	private void jmiProductTypeAddActionPerformed(java.awt.event.ActionEvent evt) {
		ProductTypeInterFrm productTypeInterFrm = new ProductTypeInterFrm();
		productTypeInterFrm.setVisible(true);
		this.table.add(productTypeInterFrm);
	}

	private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {
		int result = JOptionPane.showConfirmDialog(null, "是否退出系统");
		if (result == 0) {
			this.dispose();//观看它的传值然后定义变量
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrm().setVisible(true);
			}
		});
	}
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jmiExit;
	private javax.swing.JMenuItem jmiProductAdd;
	private javax.swing.JMenuItem jmiProductModify;
	private javax.swing.JMenuItem jmiProductTypeAdd;
	private javax.swing.JMenuItem jmiProductTypeModify;
	private javax.swing.JDesktopPane table;
	private JMenu menu;
	private JMenu menu_1;
	// End of variables declaration//GEN-END:variables

}