/*
 * ViewMainFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.view;

import java.awt.Font;

import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.SystemColor;

/**
 *
 * @author  __USER__
 */
public class ViewMainFrm extends javax.swing.JFrame {

	/** Creates new form ViewMainFrm */
	public ViewMainFrm() {
		//∏ƒ±‰œµÕ≥ƒ¨»œ◊÷ÃÂ
		Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource) {
				UIManager.put(key, font);
			}
		}

		initComponents();
		//…Ë÷√frameæ”÷–œ‘ æ
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jb_viewProduct = new javax.swing.JButton();
		jb_viewProduct.setFont(new Font("Œ¢»Ì—≈∫⁄", Font.PLAIN, 12));
		jb_viewProduct.setBackground(SystemColor.activeCaptionBorder);
		jb_ManagetLogOn = new javax.swing.JButton();
		jb_ManagetLogOn.setFont(new Font("Œ¢»Ì—≈∫⁄", Font.PLAIN, 12));
		jb_ManagetLogOn.setBackground(SystemColor.activeCaptionBorder);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new Font("Œ¢»Ì—≈∫⁄", Font.PLAIN, 27));
		jLabel1.setText("\u5B66\u751F\u95F2\u7F6E\u7269\u54C1\u4EA4\u6613\u5E73\u53F0");

		jb_viewProduct.setText("\u4E70\u5BB6\u670D\u52A1\u4E2D\u5FC3");
		jb_viewProduct.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_viewProductActionPerformed(evt);
			}
		});

		jb_ManagetLogOn.setText("\u5356\u5BB6\u670D\u52A1\u4E2D\u5FC3");
		jb_ManagetLogOn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_ManagetLogOnActionPerformed(evt);
			}
		});
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addGap(86)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(jb_viewProduct, GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
							.addGap(49)
							.addComponent(jb_ManagetLogOn, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE))
						.addComponent(jLabel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
					.addGap(110))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jb_ManagetLogOn, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
						.addComponent(jb_viewProduct, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(154, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jb_viewProductActionPerformed(java.awt.event.ActionEvent evt) {
		new FuntionMainFrm().setVisible(true);
	}

	private void jb_ManagetLogOnActionPerformed(java.awt.event.ActionEvent evt) {
		new ManagerLogOnFrm().setVisible(true);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ViewMainFrm().setVisible(true);
			}
		});
	}
	private javax.swing.JLabel jLabel1;
	private javax.swing.JButton jb_ManagetLogOn;
	private javax.swing.JButton jb_viewProduct;
	// End of variables declaration//GEN-END:variables

}